### ISSUE TITLE
Academy Award/Nobel Prize query returns []

### ISSUE THREAD

**Issue by daveliepmann** [jackrusher/mundaneum#1]
From [*core.clj* line 57](https://github.com/jackrusher/mundaneum/blob/master/src/mundaneum/core.clj#L57):
```
(query
 '[:select :distinct ?pLabel
   :where [[?p (wdt :award-received) / (wdt :subclass-of) * (entity "Nobel Prize")
            _  (wdt :award-received) / (wdt :subclass-of) * (entity "Academy Awards")]]])
=> []
```

`stringify-query` of that returns `""`.

**Comment by jackrusher** [comment]
For me `stringify-query` returns:
```
(mundaneum.query/stringify-query
 '[:select :distinct ?pLabel
   :where [[?p (wdt :award-received) / (wdt :subclass-of) * (entity "Nobel Prize")
            _ (wdt :award-received) / (wdt :subclass-of) * (entity "Academy Awards")]]])
=> "SELECT DISTINCT  ?pLabel \nWHERE {\n ?p  wdt:P166 /  wdt:P279 *  wd:Q7191 ;  wdt:P166 /  wdt:P279 *  wd:Q19020 .\n SERVICE wikibase:label { bd:serviceParam wikibase:language \"en,de,fr,es,it,ca,nl\" . }\n}"
```
... but the query itself returns `[]`. I imagine this represents a data change on their end. Will investigate.

**Comment by daveliepmann** [comment]
[Talk page of P166](https://www.wikidata.org/wiki/Property_talk:P166#.22subclass_of.22_or_.22instance_of.22_.22award.22.3F) suggests that it's due to change from `subclass-of` to `instance-of`; testing confirms it. Note substitution of "instance" for "subclass":

```
  (query
   '[:select :distinct ?pLabel
     :where [[?p (wdt :award-received) / (wdt :instance-of) * (entity "Nobel Prize")
               _ (wdt :award-received) / (wdt :instance-of) * (entity "Academy Awards")]]])
=>  [{:pLabel "Bob Dylan"} {:pLabel "George Bernard Shaw"}]
```

I don't understand why it works for you.

**Comment by jackrusher** [comment]
The query returns `[]` for me too! The change to `:instance-of` happened *after* I wrote this demo code. :)

**Comment by daveliepmann** [comment]
Oops, conflated the "fragile af" `stringify-query` difference with the return values
