### ISSUE TITLE
Enhancement Suggestion:  add a Values clause

### ISSUE THREAD

**Issue by zachcp** [jackrusher/mundaneum#13]
Jack,

It would be nice to be able to pass in multiple values to a query. It seems you have provided [one example of how to do it](https://github.com/jackrusher/mundaneum/blob/master/src/mundaneum/examples.clj#L160-L176), but I wonder if it would be worth adding a`VALUES` option - here is an example although I realize this gets in to symbol resolution which you seem to have been used only explicitly within `template` calls.

zach cp

```sparql
SELECT  ?compoundLabel 
WHERE {

 ?compound  wdt:P235 ?inchi .
 VALUES ?inchi {"QFJCIRLUMZQUOT-HPLJOQBZSA-N" 
                "MTCJZZBQNCXKAP-KSYZLYKTSA-N" 
                "YNCMLFHHXWETLD-UHFFFAOYSA-N" }
 SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" . }
}

```

```clojure
(def inchikeys
    {"QFJCIRLUMZQUOT-HPLJOQBZSA-N" 
     "MTCJZZBQNCXKAP-KSYZLYKTSA-N" 
     "YNCMLFHHXWETLD-UHFFFAOYSA-N" }

(query
    '[:select ?compoundLabel
      :where [[?compound (wdt :InChIKey) ?inchi]]
      :values ?inchi inchikeys])


```

**Comment by jackrusher** [comment]
Good idea! This should be a pretty easy contrib if you want to give it a try?

**Comment by zachcp** [comment]
sure!

**Comment by jackrusher** [comment]
Solved by move to Flint.
