### ISSUE TITLE
(entity "ระยอง") doesn't work.

### ISSUE THREAD

**Issue by veer66** [jackrusher/mundaneum#5]
````Clojure
(require '[mundaneum.query :refer [entity]])
(entity "ระยอง")
````
It returned nil, which I suppose it shouldn't.

**Comment by jackrusher** [comment]
As per the README, entity resolution is:

> currently sadly restricted to English in this code

I intend to add an optional second parameter to those functions plus a dynamic variable to set the default language, but currently everything is hard-coded to use English labels.

**Comment by veer66** [comment]
I should have label this issue as a feature request.

**Comment by jackrusher** [comment]
I've fixed `entity` to use the  `mundaneum.query/*default-language*` dynamic variable to control which language is to be used for queries. One can now bind that variable like this:
```
(binding [mundaneum.query/*default-language* "th"]
 (entity "ระยอง"))
;;=>"Q395325"
```
I'll push the update after I've fixed the weird problem with the test runner. :)
