### ISSUE TITLE
Testing by clj -Atest failed

### ISSUE THREAD

**Issue by veer66** [jackrusher/mundaneum#6]
Testing by clj -Atest failed because:

````
Caused by: java.lang.RuntimeException: Unable to resolve symbol: entity in this context
````

**Comment by jackrusher** [comment]
Yeah, as per this comment the tests only work from inside emacs:

https://github.com/jackrusher/mundaneum/blob/1038471bb40489e2e03d6d26895243c8970dad3d/deps.edn#L11

I haven't taken the time to figure out why because I do all my work in emacs.

**Comment by jackrusher** [comment]
The tests are fixed in the version I will push shortly.
